In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
import pandas as pd

customer_360 = pd.read_csv(
    "../data/processed/customer_360.csv",
    parse_dates=[
        "first_purchase_date",
        "last_purchase_date"
    ]
)

customer_360.shape

(96096, 29)

In [3]:
customer_360["active_months"].describe()

count    96096.000000
mean         0.090384
std          0.846445
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         21.100000
Name: active_months, dtype: float64

In [4]:
customer_360.columns.tolist()

['customer_unique_id',
 'total_orders',
 'total_items',
 'total_spent',
 'total_freight',
 'unique_products',
 'unique_sellers',
 'avg_order_value',
 'last_purchase_date',
 'recency_days',
 'first_purchase_date',
 'customer_lifetime_days',
 'active_months',
 'avg_review_score',
 'total_reviews',
 'has_review',
 'total_payment',
 'avg_payment_value',
 'total_payment_records',
 'max_installments',
 'credit_card_payments',
 'boleto_payments',
 'voucher_payments',
 'debit_card_payments',
 'avg_delivery_days',
 'max_delivery_days',
 'avg_delivery_delay',
 'late_orders',
 'on_time_orders']

In [5]:
# purchase_frequency

In [6]:
customer_360["active_months"].describe()

count    96096.000000
mean         0.090384
std          0.846445
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         21.100000
Name: active_months, dtype: float64

In [7]:
# purchase_frequency

customer_360["purchase_frequency"] = (
    customer_360["total_orders"] /
    customer_360["active_months"].clip(lower=1)
)

In [8]:
customer_360["purchase_frequency"].describe()

count    96096.000000
mean         1.010582
std          0.153080
min          0.098684
25%          1.000000
50%          1.000000
75%          1.000000
max          6.000000
Name: purchase_frequency, dtype: float64

In [9]:
customer_360[
    [
        "total_orders",
        "active_months",
        "purchase_frequency"
    ]
].head(10)

   total_orders  active_months  purchase_frequency
0             1            0.0                 1.0
1             1            0.0                 1.0
2             1            0.0                 1.0
3             1            0.0                 1.0
4             1            0.0                 1.0
5             1            0.0                 1.0
6             1            0.0                 1.0
7             1            0.0                 1.0
8             1            0.0                 1.0
9             1            0.0                 1.0

In [11]:
customer_360.columns.tolist()

['customer_unique_id',
 'total_orders',
 'total_items',
 'total_spent',
 'total_freight',
 'unique_products',
 'unique_sellers',
 'avg_order_value',
 'last_purchase_date',
 'recency_days',
 'first_purchase_date',
 'customer_lifetime_days',
 'active_months',
 'avg_review_score',
 'total_reviews',
 'has_review',
 'total_payment',
 'avg_payment_value',
 'total_payment_records',
 'max_installments',
 'credit_card_payments',
 'boleto_payments',
 'voucher_payments',
 'debit_card_payments',
 'avg_delivery_days',
 'max_delivery_days',
 'avg_delivery_delay',
 'late_orders',
 'on_time_orders',
 'purchase_frequency']

In [12]:
customer_360["spend_per_item"] = (
    customer_360["total_spent"] /
    customer_360["total_items"].clip(lower=1)
)

In [14]:
customer_360.columns.tolist()

['customer_unique_id',
 'total_orders',
 'total_items',
 'total_spent',
 'total_freight',
 'unique_products',
 'unique_sellers',
 'avg_order_value',
 'last_purchase_date',
 'recency_days',
 'first_purchase_date',
 'customer_lifetime_days',
 'active_months',
 'avg_review_score',
 'total_reviews',
 'has_review',
 'total_payment',
 'avg_payment_value',
 'total_payment_records',
 'max_installments',
 'credit_card_payments',
 'boleto_payments',
 'voucher_payments',
 'debit_card_payments',
 'avg_delivery_days',
 'max_delivery_days',
 'avg_delivery_delay',
 'late_orders',
 'on_time_orders',
 'purchase_frequency',
 'spend_per_item']

In [15]:
customer_360.shape

(96096, 31)

In [16]:
customer_360[
    [
        "total_spent",
        "total_items",
        "spend_per_item"
    ]
].head(10)

   total_spent  total_items  spend_per_item
0       141.90          1.0          141.90
1        27.19          1.0           27.19
2        86.22          1.0           86.22
3        43.62          1.0           43.62
4       196.89          1.0          196.89
5       166.98          1.0          166.98
6        35.38          1.0           35.38
7       419.18          2.0          209.59
8       150.12          1.0          150.12
9       129.76          1.0          129.76

In [17]:
customer_360["spend_per_item"].describe()

count    96096.000000
mean       145.710967
std        198.691445
min          0.000000
25%         57.275000
50%         95.912500
75%        162.650000
max       6929.310000
Name: spend_per_item, dtype: float64

In [18]:
customer_360.shape

(96096, 31)

In [19]:
# orders_per_seller

customer_360["orders_per_seller"] = (
    customer_360["total_orders"] /
    customer_360["unique_sellers"].clip(lower=1)
)

In [20]:
customer_360["orders_per_seller"].describe()

count    96096.000000
mean         0.994478
std          0.065181
min          0.200000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: orders_per_seller, dtype: float64

In [21]:
customer_360[
    [
        "total_orders",
        "unique_sellers",
        "orders_per_seller"
    ]
].head(10)

   total_orders  unique_sellers  orders_per_seller
0             1             1.0                1.0
1             1             1.0                1.0
2             1             1.0                1.0
3             1             1.0                1.0
4             1             1.0                1.0
5             1             1.0                1.0
6             1             1.0                1.0
7             1             1.0                1.0
8             1             1.0                1.0
9             1             1.0                1.0

In [23]:
# products_per_order

customer_360["products_per_order"] = (
    customer_360["unique_products"] /
    customer_360["total_orders"].clip(lower=1)
)

In [24]:
customer_360["products_per_order"].describe()

count    96096.000000
mean         1.029184
std          0.235579
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          8.000000
Name: products_per_order, dtype: float64

In [25]:
customer_360[
    [
        "total_orders",
        "unique_products",
        "products_per_order"
    ]
].head(10)

   total_orders  unique_products  products_per_order
0             1              1.0                 1.0
1             1              1.0                 1.0
2             1              1.0                 1.0
3             1              1.0                 1.0
4             1              1.0                 1.0
5             1              1.0                 1.0
6             1              1.0                 1.0
7             1              2.0                 2.0
8             1              1.0                 1.0
9             1              1.0                 1.0

In [26]:
customer_360.shape

(96096, 33)

In [27]:

# freight_cost_ratio

customer_360["freight_cost_ratio"] = (
    customer_360["total_freight"] / 
    customer_360["total_spent"].clip(lower =1)
)

In [28]:
customer_360["freight_cost_ratio"].describe()

count    96096.000000
mean         0.206496
std          0.125775
min          0.000000
25%          0.115044
50%          0.182088
75%          0.273607
max          0.955451
Name: freight_cost_ratio, dtype: float64

In [29]:
customer_360[
    [
        "total_spent",
        "total_freight",
        "freight_cost_ratio"
    ]
].head(10)

   total_spent  total_freight  freight_cost_ratio
0       141.90          12.00            0.084567
1        27.19           8.29            0.304892
2        86.22          17.22            0.199722
3        43.62          17.63            0.404172
4       196.89          16.89            0.085784
5       166.98          12.98            0.077734
6        35.38           7.39            0.208875
7       419.18          37.18            0.088697
8       150.12          15.12            0.100719
9       129.76          24.86            0.191584

In [35]:
customer_360["freight_cost_ratio"].value_counts(normalize=True) * 100

freight_cost_ratio
0.000000    1.048951
0.227794    0.314269
0.183256    0.190435
0.431429    0.172744
0.260741    0.115509
              ...
0.630926    0.001041
0.075245    0.001041
0.031940    0.001041
0.240599    0.001041
0.232797    0.001041
Name: proportion, Length: 45333, dtype: float64

In [36]:
# payment_to_spent_ratio

customer_360["payment_to_spent_ratio"] = (
    customer_360["total_payment"] /
    customer_360["total_spent"].clip(lower =1)
)

In [37]:
customer_360["payment_to_spent_ratio"].describe()

count    96096.000000
mean         2.471555
std         33.590261
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max       3782.190000
Name: payment_to_spent_ratio, dtype: float64

In [38]:
customer_360[
    [
        "total_spent",
        "total_payment",
        "payment_to_spent_ratio"
    ]
].head(10)

   total_spent  total_payment  payment_to_spent_ratio
0       141.90         141.90                     1.0
1        27.19          27.19                     1.0
2        86.22          86.22                     1.0
3        43.62          43.62                     1.0
4       196.89         196.89                     1.0
5       166.98         166.98                     1.0
6        35.38          35.38                     1.0
7       419.18         419.18                     1.0
8       150.12         150.12                     1.0
9       129.76         129.76                     1.0

In [39]:
# review_engagement

In [40]:
customer_360["review_engagement"] = (
    customer_360["total_reviews"] /
    customer_360["total_orders"].clip(lower =1)
)

In [41]:
customer_360["review_engagement"].describe()

count    96096.000000
mean         0.995497
std          0.099839
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: review_engagement, dtype: float64

In [42]:
customer_360[
    customer_360["review_engagement"] > 1
][
    [
        "customer_unique_id",
        "total_orders",
        "total_reviews",
        "review_engagement"
    ]
].head(10)

,customer_unique_id,total_orders,total_reviews,review_engagement
15,000bfa1d2f1a41876493be685390d6d3,1,2,2.000000
312,00cc12a6d8b578b8ebd21ea4e2ae8b27,2,4,2.000000
726,01ea7dfdac01a4e8fbe2902b73510b20,2,3,1.500000
1120,02fbe4db886eb98774c8ba300d39fa79,2,3,1.500000
1184,031e19fc630c4121f1238716f41675c3,2,4,2.000000
1910,050555c26479bbb8ba0740c37e7454d0,2,3,1.500000
2495,06a52782a04f0086d16b9c22d0e29438,3,5,1.666667
2659,0710e0c85fe7cb494d624e0863782e46,2,3,1.500000
2801,076b7055bea51da430d6a6fa054e5075,2,3,1.500000
2976,07df27b714016cb827c99ec2ecd5ebfb,2,3,1.500000

In [47]:
customer_360 = customer_360.drop(
    columns = ["review_engagement"]
)

In [48]:
# seller_diversity

customer_360["seller_diversity"] = (
    customer_360["unique_sellers"] /
    customer_360["total_orders"].clip(lower=1)
)

In [49]:
customer_360["seller_diversity"].describe()

count    96096.000000
mean         1.005691
std          0.146447
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
Name: seller_diversity, dtype: float64

In [50]:
customer_360[
    [
        "total_orders",
        "unique_sellers",
        "seller_diversity"
    ]
].head(10)

   total_orders  unique_sellers  seller_diversity
0             1             1.0               1.0
1             1             1.0               1.0
2             1             1.0               1.0
3             1             1.0               1.0
4             1             1.0               1.0
5             1             1.0               1.0
6             1             1.0               1.0
7             1             1.0               1.0
8             1             1.0               1.0
9             1             1.0               1.0

In [51]:
# customer_value_score

customer_360["spend_per_order"] = (
    customer_360["total_spent"] /
    customer_360["total_orders"].clip(lower =1)
)

In [52]:
customer_360["spend_per_order"].describe()

count    96096.000000
mean       159.810187
std        220.564409
min          0.000000
25%         61.690000
50%        105.180000
75%        176.230000
max      13664.080000
Name: spend_per_order, dtype: float64

In [53]:
customer_360[
    [
        "total_spent",
        "total_orders",
        "spend_per_order",
        "avg_order_value"
    ]
].head(10)

   total_spent  total_orders  spend_per_order  avg_order_value
0       141.90             1           141.90           141.90
1        27.19             1            27.19            27.19
2        86.22             1            86.22            86.22
3        43.62             1            43.62            43.62
4       196.89             1           196.89           196.89
5       166.98             1           166.98           166.98
6        35.38             1            35.38            35.38
7       419.18             1           419.18           419.18
8       150.12             1           150.12           150.12
9       129.76             1           129.76           129.76

In [54]:
customer_360[
    [
        "customer_unique_id",
        "recency_days",
        "total_orders",
        "total_spent"
    ]
].describe()

       recency_days  total_orders   total_spent
count  96096.000000  96096.000000  96096.000000
mean     287.735691      1.034809    164.872141
std      153.414676      0.214384    227.938658
min        0.000000      1.000000      0.000000
25%      163.000000      1.000000     62.390000
50%      268.000000      1.000000    107.270000
75%      397.000000      1.000000    182.237500
max      772.000000     17.000000  13664.080000

In [55]:
# Create RFM scores

# — Recency	recency_days	How recently the customer purchased
# F — Frequency	total_orders	How many orders the customer made
# M — Monetary	total_spent	How much the customer spen

In [ ]:
# Create RFM scores
#We'll use 5 quantile groups (1–5) so customers are ranked relative to other customers.#

#Create F_score
customer_360["R_score"] = pd.qcut(
    customer_360["recency_days"],
    q = 5,
    labels = [5,4,3,2,1],
    duplicates= "drop"
)

In [61]:
customer_360["F_score"] = pd.qcut(
    customer_360["total_orders"].rank(method = "first"),
    q=5,
    labels = [1,2,3,4,5],
    duplicates = "drop"
)

In [62]:
# Create M_score
# Higher spending = better:

customer_360["M_score"] = pd.qcut(
    customer_360["total_spent"],
    q = 5,
    labels = [1,2,3,4,5],
    duplicates= "drop"
)

In [65]:
# check the scores
customer_360[
    ["recency_days", "total_orders", "total_spent",
     "R_score", "F_score", "M_score"]  
].head()

   recency_days  total_orders  total_spent R_score F_score M_score
0           160             1       141.90       4       1       4
1           163             1        27.19       4       1       1
2           585             1        86.22       1       1       2
3           369             1        43.62       2       1       1
4           336             1       196.89       2       1       4

In [66]:
customer_360[
    ["R_score", "F_score", "M_score"]
].describe()

        R_score  F_score  M_score
count     96096    96096    96096
unique        5        5        5
top           5        1        2
freq      19324    19220    19228

In [68]:
# Create the combined RFM_score

customer_360["RFM_score"] = (
    customer_360["R_score"].astype(int)
    + customer_360["F_score"].astype(int)
    + customer_360["M_score"].astype(int)
)

In [69]:
customer_360["RFM_score"]

0         9
1         6
2         4
3         4
4         7
         ..
96091    11
96092    10
96093     9
96094    13
96095     8
Name: RFM_score, Length: 96096, dtype: int64

In [70]:
customer_360["RFM_score"].describe()

count    96096.000000
mean         9.003736
std          2.504101
min          3.000000
25%          7.000000
50%          9.000000
75%         11.000000
max         15.000000
Name: RFM_score, dtype: float64

In [71]:
customer_360[
    [
        "recency_days",
        "total_orders",
        "total_spent",
        "R_score",
        "F_score",
        "M_score",
        "RFM_score"
    ]
].head(10)

   recency_days  total_orders  total_spent R_score F_score M_score  RFM_score
0           160             1       141.90       4       1       4          9
1           163             1        27.19       4       1       1          6
2           585             1        86.22       1       1       2          4
3           369             1        43.62       2       1       1          4
4           336             1       196.89       2       1       4          7
5           194             1       166.98       4       1       4          9
6           180             1        35.38       4       1       1          6
7           231             1       419.18       3       1       5          9
8           591             1       150.12       1       1       4          6
9           219             1       129.76       4       1       3          8

In [72]:
# Create customer segments
# RFM Score	Segment
# 13–15	High Value
# 10–12	Loyal
# 7–9	Potential
# 3–6	Low ValueR

In [73]:
customer_360["customer_segment"] = pd.cut(
    customer_360["RFM_score"],
    bins = [2,6,9,12,15],
    labels = [
        "Low Value",
        "Potential",
        "Loyal",
        "High Value"
    ]
)

In [74]:
customer_360["customer_segment"].value_counts().sort_index()

customer_segment
Low Value     15926
Potential     39444
Loyal         32417
High Value     8309
Name: count, dtype: int64

In [75]:
customer_360[
    [
        "RFM_score",
        "customer_segment"
    ]
].head(10)

   RFM_score customer_segment
0          9        Potential
1          6        Low Value
2          4        Low Value
3          4        Low Value
4          7        Potential
5          9        Potential
6          6        Low Value
7          9        Potential
8          6        Low Value
9          8        Potential

In [76]:
customer_360["customer_segment"].value_counts()

customer_segment
Potential     39444
Loyal         32417
Low Value     15926
High Value     8309
Name: count, dtype: int64

In [77]:
customer_360["customer_segment"].value_counts(normalize = True) * 100

customer_segment
Potential     41.046454
Loyal         33.733974
Low Value     16.573010
High Value     8.646562
Name: proportion, dtype: float64

In [78]:
# customer_value_score

# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# customer_360[
#     ["total_spent", "total_orders"]
# ] = scaler.fit_transform(
#     customer_360[
#         ["total_spent", "total_orders"]
#     ]
# )

In [81]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_values = scaler.fit_transform(
    customer_360[
        ["total_spent", "total_orders"]
    ]
)

customer_360["spend_score"] = scaled_values[:, 0]
customer_360["frequency_score"] = scaled_values[:,1]

In [82]:
customer_360[
    [
        "total_spent",
        "total_orders",
        "spend_score",
        "frequency_score"
    ]
].head(10)

   total_spent  total_orders  spend_score  frequency_score
0       141.90             1     0.010385              0.0
1        27.19             1     0.001990              0.0
2        86.22             1     0.006310              0.0
3        43.62             1     0.003192              0.0
4       196.89             1     0.014409              0.0
5       166.98             1     0.012220              0.0
6        35.38             1     0.002589              0.0
7       419.18             1     0.030678              0.0
8       150.12             1     0.010986              0.0
9       129.76             1     0.009496              0.0

In [83]:
# Create customer_value_score

In [84]:
customer_360["customer_value_score"] = (
    0.7 * customer_360["spend_score"] +
    0.3 * customer_360["frequency_score"]
)

In [85]:
customer_360["customer_value_score"].describe()

count    96096.000000
mean         0.009099
std          0.012806
min          0.000000
25%          0.003202
50%          0.005535
75%          0.009647
max          0.700000
Name: customer_value_score, dtype: float64

In [86]:
customer_360[
    [
        "total_spent",
        "total_orders",
        "spend_score",
        "frequency_score",
        "customer_value_score"
    ]
].head(10)

,total_spent,total_orders,spend_score,frequency_score,customer_value_score
0,141.90,1,0.010385,0.0,0.007269
1,27.19,1,0.001990,0.0,0.001393
2,86.22,1,0.006310,0.0,0.004417
3,43.62,1,0.003192,0.0,0.002235
4,196.89,1,0.014409,0.0,0.010087
5,166.98,1,0.012220,0.0,0.008554
6,35.38,1,0.002589,0.0,0.001812
7,419.18,1,0.030678,0.0,0.021474
8,150.12,1,0.010986,0.0,0.007691
9,129.76,1,0.009496,0.0,0.006648

In [87]:
new_features = [
    "purchase_frequency",
    "spend_per_item",
    "orders_per_seller",
    "products_per_order",
    "freight_cost_ratio",
    "payment_to_spent_ratio",
    "seller_diversity",
    "spend_per_order",
    "R_score",
    "F_score",
    "M_score",
    "RFM_score",
    "customer_segment",
    "spend_score",
    "frequency_score",
    "customer_value_score"
]

customer_360[new_features].describe(include="all")

,purchase_frequency,spend_per_item,orders_per_seller,products_per_order,freight_cost_ratio,payment_to_spent_ratio,seller_diversity,spend_per_order,R_score,F_score,M_score,RFM_score,customer_segment,spend_score,frequency_score,customer_value_score
count,96096.000000,96096.000000,96096.000000,96096.000000,96096.000000,96096.000000,96096.000000,96096.000000,96096.0,96096.0,96096.0,96096.000000,96096,96096.000000,96096.000000,96096.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,NaN,4,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,NaN,Potential,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19324.0,19220.0,19228.0,NaN,39444,NaN,NaN,NaN
mean,1.010582,145.710967,0.994478,1.029184,0.206496,2.471555,1.005691,159.810187,NaN,NaN,NaN,9.003736,NaN,0.012066,0.002176,0.009099
std,0.153080,198.691445,0.065181,0.235579,0.125775,33.590261,0.146447,220.564409,NaN,NaN,NaN,2.504101,NaN,0.016682,0.013399,0.012806
min,0.098684,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,3.000000,NaN,0.000000,0.000000,0.000000
25%,1.000000,57.275000,1.000000,1.000000,0.115044,1.000000,1.000000,61.690000,NaN,NaN,NaN,7.000000,NaN,0.004566,0.000000,0.003202
50%,1.000000,95.912500,1.000000,1.000000,0.182088,1.000000,1.000000,105.180000,NaN,NaN,NaN,9.000000,NaN,0.007851,0.000000,0.005535
75%,1.000000,162.650000,1.000000,1.000000,0.273607,1.000000,1.000000,176.230000,NaN,NaN,NaN,11.000000,NaN,0.013337,0.000000,0.009647
max,6.000000,6929.310000,3.000000,8.000000,0.955451,3782.190000,5.000000,13664.080000,NaN,NaN,NaN,15.000000,NaN,1.000000,1.000000,0.700000

In [90]:
customer_360[new_features].isnull().sum()

purchase_frequency        0
spend_per_item            0
orders_per_seller         0
products_per_order        0
freight_cost_ratio        0
payment_to_spent_ratio    0
seller_diversity          0
spend_per_order           0
R_score                   0
F_score                   0
M_score                   0
RFM_score                 0
customer_segment          0
spend_score               0
frequency_score           0
customer_value_score      0
dtype: int64

In [91]:
customer_360.shape

(96096, 45)

In [92]:
[x for x in customer_360.columns if "_x" in x or "_y" in x]

[]

In [93]:
customer_360.to_csv(
    "../data/processed/customer_360_feature_engineered.csv",
    index=False
)

In [94]:
import os

os.path.exists(
    "../data/processed/customer_360_feature_engineered.csv"
)

True